application      = "IO"
cloud            = "AWS"
creator          = "Jacob Sanders"
environment      = "Development"
organization     = "Organization"
profile          = "default"
region           = "us-east-1"
service          = "VPC"